//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cvicenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cvicenie()
        {
            this.faktura = new HashSet<faktura>();
            this.inventar = new HashSet<inventar>();
        }
    
        public int cislo_cvicenia { get; set; }
        public string meno_dietata { get; set; }
        public string priezvisko_dietata { get; set; }
        public string datum_cvicenia { get; set; }
        public int dlzka_cvicenia { get; set; }
        public bool prebehlo { get; set; }
        public string pokrok { get; set; }
        public string poznamka { get; set; }
        public int zakaznik_id { get; set; }
        public string mesacny_vykaz_id { get; set; }
        public Nullable<int> permanentka_id { get; set; }
    
        public virtual permanentka permanentka { get; set; }
        public virtual zakaznik zakaznik { get; set; }
        public virtual mesacny_vykaz mesacny_vykaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faktura> faktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventar> inventar { get; set; }
    }
}
