//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class faktura
    {
        public int cislo_faktury { get; set; }
        public string typ { get; set; }
        public string meno { get; set; }
        public string priezvisko { get; set; }
        public string datum_cvicenia { get; set; }
        public string datum_vystavenia { get; set; }
        public int suma { get; set; }
        public string sposob_uhrady { get; set; }
        public int zakaznik_id { get; set; }
        public int sablona_id { get; set; }
        public Nullable<int> cvicenie_id { get; set; }
    
        public virtual cvicenie cvicenie { get; set; }
        public virtual sablona sablona { get; set; }
        public virtual zakaznik zakaznik { get; set; }
    }
}
