//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventar()
        {
            this.cvicenie = new HashSet<cvicenie>();
        }
    
        public int id { get; set; }
        public string nazov { get; set; }
        public string datum_kupy { get; set; }
        public string typ { get; set; }
        public string servis { get; set; }
        public bool k_prevadzke { get; set; }
        public string poznamka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cvicenie> cvicenie { get; set; }
    }
}
