//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesacny_vykaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mesacny_vykaz()
        {
            this.cvicenie = new HashSet<cvicenie>();
            this.podujatie = new HashSet<podujatie>();
        }
    
        public string mesiac { get; set; }
        public Nullable<int> najom { get; set; }
        public Nullable<bool> najom_zaplatene { get; set; }
        public Nullable<int> odvody { get; set; }
        public Nullable<bool> odvody_zaplatene { get; set; }
        public Nullable<int> cviceni_celkovo { get; set; }
        public Nullable<int> vyzbierane_peniaze_celkovo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cvicenie> cvicenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<podujatie> podujatie { get; set; }
    }
}
