//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public osoba()
        {
            this.zmluva = new HashSet<zmluva>();
        }
    
        public int ID { get; set; }
        public string Meno { get; set; }
        public string Priezvisko { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Ulica { get; set; }
        public string Mesto { get; set; }
        public string Login_meno { get; set; }
        public string Login_heslo { get; set; }
        public string Typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zmluva> zmluva { get; set; }
    }
}
