//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class permanentka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public permanentka()
        {
            this.cvicenie = new HashSet<cvicenie>();
        }
    
        public int cislo_permanentky { get; set; }
        public string meno_dietata { get; set; }
        public string priezvisko_dietata { get; set; }
        public string pocet_cviceni { get; set; }
        public string datum_kupy { get; set; }
        public int zakaznik_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cvicenie> cvicenie { get; set; }
        public virtual zakaznik zakaznik { get; set; }
    }
}
