//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class podujatie
    {
        public int id { get; set; }
        public string nazov { get; set; }
        public string ulica { get; set; }
        public string mesto { get; set; }
        public string datum_podujatia { get; set; }
        public string cas_zacatia { get; set; }
        public string doba_trvania { get; set; }
        public Nullable<int> vyhradene_peniaze { get; set; }
        public Nullable<int> pocet_osob { get; set; }
        public Nullable<int> vyzbierane_peniaze { get; set; }
        public string poznamka { get; set; }
        public string mesacny_vykaz_id { get; set; }
    
        public virtual mesacny_vykaz mesacny_vykaz { get; set; }
    }
}
