//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skuska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zmluva
    {
        public string cislo_zmluvy { get; set; }
        public string typ { get; set; }
        public string meno { get; set; }
        public string priezvisko { get; set; }
        public string ulica { get; set; }
        public string mesto { get; set; }
        public string cislo_op { get; set; }
        public string rodne_cislo { get; set; }
        public string cislo_uctu { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string datum_zacatia { get; set; }
        public string datum_konca { get; set; }
        public string datum_vystavenia { get; set; }
        public Nullable<int> hodinova_mzda { get; set; }
        public string poznamka { get; set; }
        public int osoba_id { get; set; }
        public int sablona_id { get; set; }
    
        public virtual osoba osoba { get; set; }
        public virtual sablona sablona { get; set; }
    }
}
